# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f84e986c08eba991b9209a77f780b16ed9497c63a52bee42e8846c968db4b5e668e67603f3b137a0db83ef8bf22a641fc0f116f0a618f31f77d01306e140f9

test:
  secret_key_base: ed412fc3557f6118b359d67e56a152de03fc9d70ec8cebc494d01e7574ca51b056d07de4533b41e88089aca7739bb3a0cabd3c526e34302f9c00c9bdd8458fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
